### ISSUE TITLE
Can you release the latest version of fmin?

### ISSUE THREAD

**Issue by connono** [benfred/fmin#13]
I found that fmin had been modified in 2018 without a new release. Can you release the latest version of fmin?

**Comment by SukkaW** [comment]
@benfred Just a friendly ping on this.

The latest version of `fmin` on npm (which is `0.0.2`) declares `rollup`, `jshint`, `tape` and so on as `devDependencies`. Though the `fmin` has already corrects this, but the fixes were never published to the npm.

**Comment by lloydjatkinson** [comment]
I hope #16 is a prompt to deploy these changes

**Comment by exoego** [comment]
> The latest version of fmin on npm (which is 0.0.2) declares rollup, jshint, tape and so on as devDependencies. Though the fmin has already corrected this on GitHub, but the fixes were never published to the npm.

Yes, it is very helpful if new version with https://github.com/benfred/fmin/commit/8974eb211dce463036de581fa6f3cae7925a5a52 get published

**Comment by exoego** [comment]
My workaround to exclude fmin's accidentally-included dependencies


## Yarn

1. Add `resolutions` to package.json:

```json
  "resolutions": {
    "fmin/rollup": "npm:empty-npm-package@1.0.0",
    "fmin/json2module": "npm:empty-npm-package@1.0.0",
    "fmin/tape": "npm:empty-npm-package@1.0.0",
    "fmin/uglify-js": "npm:empty-npm-package@1.0.0"
  },
```

2. Then, run `yarn add fmin`. 

## NPM

1. Add `overrides` to package.json:

```json
  "overrides": {
    "fmin": {
      "rollup": "npm:empty-npm-package@1.0.0",
      "json2module": "npm:empty-npm-package@1.0.0",
      "tape": "npm:empty-npm-package@1.0.0",
      "uglify-js": "npm:empty-npm-package@1.0.0"
    }
  },
```

2. Then, run `npm install fmin` (with `-D` if needed).

**Comment by benfred** [comment]
pushed out latest changes to  https://www.npmjs.com/package/fmin - let me know if this resolves

**Comment by SukkaW** [comment]
@benfred Can confirm `0.0.4` includes the latest commits. Thanks!
