### ISSUE TITLE
can't npm install (using node v8.7.0)

### ISSUE THREAD

**Issue by r03ert0** [benfred/fmin#5]
When I `npm install fmin`, I get

```
npm ERR! code MODULE_NOT_FOUND
npm ERR! Cannot find module 'internal/errors'

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/roberto/.npm/_logs/2018-02-09T19_26_55_019Z-debug.log
```

**Comment by benfred** [comment]
Hmm - I just tested on OSX (w/ node v.9.3.0) and on Ubuntu (w/ node v9.2.0) and it worked in both cases. Can you install any other node modules?

**Comment by r03ert0** [comment]
oh my... you were right. Somehow I wasn't able to install anything. Had to reinstall `node` all over again. Thanks!
